# >>> Prefix >>>
set -g prefix C-Space
bind C-Space send-prefix
# <<< Prefix <<< 

# >>> Mouse Support >>>
set -g mouse on
# <<< Mouse Support <<<

# >>> Claude >>>
set -g focus-events on
# <<< Claude <<<

# >>> Vim Motions >>>
setw -g mode-keys vi

set-option -g set-clipboard on
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi 'MouseDragEnd1Pane' send -X copy-pipe-and-cancel "pbcopy"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H swap-pane -t '{left-of}'
bind -r J swap-pane -t '{down-of}'
bind -r K swap-pane -t '{up-of}'
bind -r L swap-pane -t '{right-of}'
# <<< Vim Motions <<<

# >>> Window Splitting >>>
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
# <<< Window Splitting <<<

# >>> Window Status Styling >>>
set -g window-status-current-format " #I:#W#{?@agent_state, #{@agent_state},} "
set -g window-status-current-style bold
set -g window-status-activity-style default
set -g window-status-bell-style default
set -g window-status-format "#{?window_last_flag,#[italics],}#[nobold] #I:#W#{?@agent_state, #{@agent_state},} #[default]"
# <<< Window Status Styling <<<
