# >>> Prefix >>>
set -g prefix C-Space
bind C-Space send-prefix
# <<< Prefix <<< 

# >>> Mouse Support >>>
set -g mouse on
# <<< Mouse Support <<<

# >>> Vim Motions >>>
setw -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# <<< Vim Motions <<<

# >>> Window Splitting >>>
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
# <<< Window Splitting <<<

